name: terraform-iac-pipeline
on: push
jobs:
  terraform-job:
    runs-on: ubuntu-22.04
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: GitLeaks Scan
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Check TF Version
        run: terraform -version

      - name: TF INIT
        run: terraform init

      - name: TF FORMAT
        run: terraform fmt

      - name: TF VALIDATE
        run: terraform validate

      - name: TF PLAN
        run: terraform plan

      - name: TF APPLY
        run: terraform apply -auto-approve
